# permissions for end users to view githttpservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githttpserver-viewer-role
rules:
- apiGroups:
  - jarpsimoes.github.io
  resources:
  - githttpservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jarpsimoes.github.io
  resources:
  - githttpservers/status
  verbs:
  - get
