apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: GitHttpServer is the Schema for the githttpservers API
      displayName: Git Http Server
      kind: GitHttpServer
      name: githttpservers.jarpsimoes.github.io
      version: v1alpha1
  description: test
  displayName: test
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - dd
  - dd
  links:
  - name: Operator
    url: https://operator.domain
  maintainers:
  - email: jarpsimoes
    name: joao
  maturity: alpha
  provider:
    name: test
  version: 0.0.0
