name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN_TESTS }}
  ACCESS_USERNAME: html_sample
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_TOKEN }}
  DOCKER_IMAGE: docker.io/jarpsimoes/git_http_server_operator
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Calc coverage
        run: make test

      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.6
        with:
          infile: cover.out
          outfile: coverage.lcov
          
#      - name: Codecov Reports
#        uses: codecov/codecov-action@v3.1.0
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          files: coverage.lcov
#          fail_ci_if_error: true 
                  
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: jarpsimoes
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: | 
          make docker-build docker-push IMG=${DOCKER_IMAGE}:v0.${SHORT_SHA}
          docker tag ${DOCKER_IMAGE}:v0.${SHORT_SHA} ${DOCKER_IMAGE}:latest
          docker push ${DOCKER_IMAGE}:latest
          make build-prod-manifests IMG=${DOCKER_IMAGE}:v0.${SHORT_SHA}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: operator-deployment
          path: dist/git-http-server-operator.yaml