name: Docker Image CI

on:
  push:
    tags: 
      - "v*"
    branches: 
      - "main"
    paths-ignore: 
      - "dist/**"
      - "*.md"
  pull_request:
    branches: [ "main" ]
  

env:
  ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN_TESTS }}
  ACCESS_USERNAME: html_sample
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_TOKEN }}
  DOCKER_IMAGE: docker.io/jarpsimoes/git_http_server_operator
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: jarpsimoes
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Docker Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: Build and push Docker image
        run: | 
          make docker-build docker-push IMG=${DOCKER_IMAGE}:${{ steps.vars.outputs.tag }}
          docker tag ${DOCKER_IMAGE}:${{ steps.vars.outputs.tag }} ${DOCKER_IMAGE}:latest
          docker push ${DOCKER_IMAGE}:latest
          make build-prod-manifests IMG=${DOCKER_IMAGE}:${{ steps.vars.outputs.tag }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: operator-deployment
          path: dist/git-http-server-operator.yaml
      - name: Git Auto Commit  
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Upload distribution file
          branch: main
          file_pattern: dist/git-http-server-operator.yaml
          commit_user_name: github-actions-bot
          commit_user_email: github-actions-bot@jarpsimoes.github.io
          commit_author: github-actions-bot <github-actions-bot@jarpsimoes.github.io>
